### ISSUE TITLE
Normalize Variants

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#128]
Left Align indels
multiallelic sites
MNPs

**Comment by jasonwalker80** [comment]
See this bam-readcount issue concerning normalization of indels:
https://github.com/genome/bam-readcount/issues/40

In that issue they list another tool for normalizing variants (including decomposition of biallelic block substitutions):
http://genome.sph.umich.edu/wiki/Vt

**Comment by jasonwalker80** [comment]
Continue with GATK LeftAlignAndTrimIndels for version 1.

**Comment by jasonwalker80** [comment]
We have been running with LeftAlign for many months. However, there are issues with A and R INFO tags in the VCF when using the --splitMultiAllelic option in GATK. Instead, we will turn off that option and add the `vt decompose` step immediately after LeftAlign. 

Then let's close this old issue. Switching to `vt` for normalization would require a revalidation of the pipelines and a comparison for type1 and type2 errors.

**Comment by susannasiebert** [comment]
I think we can close this issue, correct?
