### ISSUE TITLE
Remove or make DoCM step optional.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#220]
Regardless of how we approach generating a DoCM list, we need a version of the tumor-only workflow and paired workflow (aka detect_variants) that runs without DoCM. Since optional steps are not supported in CWL, we either use a wrapper that returns true if no DoCM input is provided or we make a new CWL that simply does not include the DoCM step/inputs.

**Comment by chrisamiller** [comment]
DoCM now runs in all somatic workflows, but by default, docm-only variants are marked as failing filters, so appear in the VCF, but not the final tabular output
