### ISSUE TITLE
Add sample concordance to paired workflows.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#289]
- concordance checking between tumor and normal bam
   - https://github.com/genome/concordance

**Comment by chrisamiller** [comment]
Consider replacing the above with https://github.com/brentp/somalier

**Comment by chrisamiller** [comment]
Just heard from brentp that somalier has a new release and a docker image (see here: https://cloud.docker.com/repository/registry-1.docker.io/brentp/somalier)

Given a bed file of SNP sites, that should make it super-easy to check concordance.  We created a very small ones here for the `gmt analysis concordance` tool, which contain SNPs with high population AF.  They may or may not be the best way to go.  (they also may or may not still exist - have to see if the feature lists got migrated to new disk)

chr1 b37 SNPS in exome region:
 /gscmnt/gc9018/info/feature_list/ccb8bd8a885b47a78eb81223ccfcb458/ccb8bd8a885b47a78eb81223ccfcb458.bed, 

mm9 SNPs:
/gscmnt/gc13023/info/feature_list/6da190b2cd394a30a5b01ef2010fa44c/6da190b2cd394a30a5b01ef2010fa44c.bed

**Comment by chrisamiller** [comment]
closed by https://github.com/genome/analysis-workflows/pull/637
