### ISSUE TITLE
Remove hardcoded files in rnaseq qc step

### ISSUE THREAD

**Issue by johnegarza** [genome/analysis-workflows#327]
As discussed in PR #326, the refFlat and interval files are currently pre-generated and hardcoded into the workflow. These can be generated during the workflow, but some additional scripting may be required. These files are created using tools from gmt, but simply requiring gmt in the docker image will introduce a large amount of dependencies that may be avoidable.

**Comment by chrisamiller** [comment]
To be fair, the GTF and the reference fasta need to be in place as well.  If it's a trivial thing to do (like "grep rRNA /path/to/gtf"), then maybe in the workflow makes sense. If it's more complex, then it falls into the "we need to rework our annotation import process" bucket
