### ISSUE TITLE
Resolve the correct strand options in RNA-seq workflow

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#333]
See comments in PR #326 for details.

**Comment by jasonwalker80** [comment]
Also, we will want to handle 'Unstranded' data. IN rnaseq/workflow.cwl it's a required input. This is likely a place to use JavaScriptExpression to resolve when we need null parameters vs. explicit unstranded options.

**Comment by chrisamiller** [comment]
This is included in the latest RNAseq CWL
