### ISSUE TITLE
QC output coverage in BigWig format file

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#467]
The docs for using `bamCoverage` to create a bigWig file:
https://deeptools.readthedocs.io/en/develop/content/list_of_tools.html#general-principles

**Comment by jasonwalker80** [comment]
Will DeepTools `bamCoverage` work on CRAM files?

**Comment by tmooney** [comment]
Looks like deeptools does have CRAM support per deeptools/deepTools#619, so hopefully this will work just fine!

**Comment by tmooney** [comment]
I've updated #548 to add it to the WGS QC process.  We should discuss what values to set for the various parameters, if any.
