### ISSUE TITLE
Germline VEP Plugins

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#586]
We would need to add the appropriate options/configuration to allow for the customization of VEP plugins run by each pipeline. Currently WILDTYPE and DOWNSTREAM are hard-coded.

> Hi guys,
> 
> There are a few VEP plugins that are very useful for the germline WGS assay. A full list can be found here:
> 
> https://useast.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
> 
> but specific ones that we should incorporate into the germline WGS assay are:
> 
> CADD
> REVEL
> ExACpLI
> LoFtool
> SpiceRegion
> 
> We should try to get this into the assay at some point.
> 
> Dave

**Comment by jasonwalker80** [comment]
@apaul7 I believe this was mostly resolved, but now there is a specific issue with the spliceregion plugin, correct?

**Comment by apaul7** [comment]
resolved with #718
