### ISSUE TITLE
Update VEP and us latest Ensembl annotation release

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#614]
We need to update the docker image to use the latest version of VEP as well as the latest version of Ensembl. The CWL workflows may or may not need to change, but this seems like the most reasonable place to track this. Specifically, we need to run the exome_workflow.tgz test using the latest version. It would be good to update the test data as well to the latest annotation.

**Comment by johnegarza** [comment]
Done:
- VEP v95 cache downloaded
- new docker image built, see genome/docker-vep_helper-cwl#4
- vep.cwl tool updated, see #622 
In progress:
- Update the test case cache in exome_workflow.tgz
- Discuss genome/docker-vep_helper-cwl#5

**Comment by johnegarza** [comment]
Cache has been updated in example data, closing issue
