### ISSUE TITLE
Run pindel on regions instead of chromosomes for Exome

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#616]
Use split interval lists to make somewhat equal "buckets" of genomic regions that are limited to the target_region. (limit to protein coding only)

**Comment by chrisamiller** [comment]
As we're phasing pindel out long term, this seems like a "won't fix" to me.  Feel free to reopen if you disagree.

**Comment by dufeiyu** [comment]
Actually this issue is already resolved via https://github.com/genome/analysis-workflows/pull/700. It should have been closed a year ago.
