### ISSUE TITLE
exome.cwl representation

### ISSUE THREAD

**Issue by serge2016** [genome/analysis-workflows#630]
Hello!
Is it possible somehow to display the entire `exome.cwl` workflow with all subworkflows and tools at once? I mean, I'd like to see a picture, where all atomic elements (=tools) are shown, not subworkflows.
Usually Rabix (http://rabix.io/) helps, but it can't represent the contents of subworkflows.
`cwltool` has a command `--pack`, but it failes with an error in this case.
So:
1. Do you know a way to generate a 'packed' cwl-scheme of workflow with links in `run` sections to commandlineTool-s only?
2. Do you know a way to generate an image with a scheme with all tools in the workflow at once?

**Comment by serge2016** [comment]
https://github.com/common-workflow-language/cwltool/issues/1103 - issue about `cwltool` error during `--pack`.

**Comment by chrisamiller** [comment]
I'm going to close this as being outside the scope of our work here.  I agree that it'd be great if Rabix or some other tool supported workflow visualization that handles this case.
