### ISSUE TITLE
add assembly flag to vep.cwl

### ISSUE THREAD

**Issue by zlskidmore** [genome/analysis-workflows#647]
An assembly flag will probably need to be added to vep.cwl, particularly if using my vepCache in /gscmnt/gc2547

Should probably be added anyway though as an option @Matthew-Mosior @chrisamiller  this will probably be needed for the mouse pipelines as well

**Comment by johnegarza** [comment]
This will be in soon, I was cleaning up today and realized #572 was never merged, that should be done today

**Comment by zlskidmore** [comment]
ah okay, just noticed it myself and thought i'd mention it
