### ISSUE TITLE
Add CLE disclaimer to certain output files

### ISSUE THREAD

**Issue by susannasiebert** [genome/analysis-workflows#664]
The following disclaimer should be added to some output file:
```
Myeloseq Assay Version 1.0 -- This laboratory developed test (LDT) was developed and its performance characteristics determined by the CLIA Licensed Environment laboratory at the McDonnell Genome Institute at Washington University (MGI-CLE, CLIA #26D2092546, CAP #9047655), Dr. David H. Spencer MD, PhD, FCAP, Medical Director. 4444 Forest Park Avenue, Rm 4127 St. Louis, Missouri 63108 (314) 286-1460 Fax: (314) 286-1810. The MGI-CLE laboratory is regulated under CLIA as certified to perform high-complexity testing. This test has not been cleared or approved by the FDA.
```

This can be done leveraging the new `add_string_at_line.cwl` and `add_string_at_line_bgzipped.cwl` tools.

We need to get a list of which files this text should be added. @dufeiyu do you know?

**Comment by jasonwalker80** [comment]
@susannasiebert I'm sending an email to request a list of output files to add the disclaimer. Is there anything else blocking this issue?

**Comment by susannasiebert** [comment]
I had talked to @dufeiyu about this briefly and also mentioned that the quoted text is not necessarily the exact text they would want to add. So we'd need to know what the comments are and which files to apply them to. Feiyu also also mentioned that he would talk to Dave Spencer about this but it would be great to get an email chain started as well (maybe cc Feiyu).
Thanks for following up on this!

**Comment by dhspence** [comment]
@susannasiebert,

This boilerplate text is what we need to insert into the final TSV files (both SV and SNV/indel). Sorry for taking so long to get it to you.

 

> This laboratory developed test (LDT) was developed and its performance characteristics determined by the CLIA Licensed Environment laboratory at the McDonnell Genome Institute at Washington University (MGI-CLE, CLIA #26D2092546, CAP #9047655), Dr. David H. Spencer MD, PhD, FCAP, Medical Director. 4444 Forest Park Avenue, Rm 4127 St. Louis, Missouri 63108 (314) 286-1460 Fax: (314) 286-1810. The MGI-CLE laboratory is regulated under CLIA as certified to perform high-complexity testing. This test has not been cleared or approved by the FDA.

Dave

**Comment by susannasiebert** [comment]
@dhspence do we need to add this to the final TSVs all of the CLE pipelines (somatic exome as well as AML trio)?

**Comment by dhspence** [comment]
Yes, it’s a boilerplate statement that should be added to all CLE pipelines. Thanks,

Dave

**Comment by susannasiebert** [comment]
Here are the TSV's I'm planning on adding the disclaimer to:
- cle_aml_trio.cwl
  - tumor_final_tsv
  - germline_final_tsv
  - full_variant_report
- cle_somatic_exome.cwl
  - final_tsv
