### ISSUE TITLE
Allow clinical types in immuno workflow

### ISSUE THREAD

**Issue by johnegarza** [genome/analysis-workflows#670]
https://github.com/genome/analysis-workflows/blob/a3e26136043c03192c38c335316d2d36e3e67478/definitions/pipelines/immuno.cwl#L731

The immuno workflow should be modified to allow the user to optionally specify clinical HLA types. These should be intersected with the optitype output using a filtering script, then passed to pvacseq

**Comment by chrisamiller** [comment]
This exists in the currently implemented immuno workflow, as far as i can tell.  @johnegarza, please reopen if I'm mistaken
