### ISSUE TITLE
Troubleshoot Spliceregion germline VEP plugin for WGS workflow

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#706]
@apaul7 please add some information on what's wrong here.

**Comment by apaul7** [comment]
There actually isn't an issue with the results produced from running the SpliceRegion plugin. The filtered variants that were parsed for tsv generation just do not have values for the SpliceRegion VEP entry. I will use the `SpliceRegion,Extended` call to get more information for the variants that do have values.
