### ISSUE TITLE
Add support for FASTQ rather than unaligned BAM pipeline inputs

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#717]
Each DNA, RNA, and WGBS should also support paired, compressed FASTQ files as inputs. This changes the order and/or the commands used during adapter trimming and alignment. For example, we can no longer pipe interleaved FASTQ from the unaligned BAM directly to BWA-MEM. Subsequent Docker image changes/additions are required to update the actual commands executed in the docker shell script wrappers. Perhaps a new FASTQ compatible wrapper in addition to the existing unaligned BAM wrapper would help facilitate the transition.

**Comment by chrisamiller** [comment]
This change will also need to include updating the example_data files and test yamls

**Comment by jasonwalker80** [comment]
I'm going to close this since we added support for either FASTQ or unaligned BAM and most workflows utilize the new sequence type. If I missed something, let's create a more specific issue that can be addressed.
