### ISSUE TITLE
Copy number reference for CNVkit

### ISSUE THREAD

**Issue by Stikus** [genome/analysis-workflows#726]
Hello. I'm trying to test your [germline_wgs.cwl](https://github.com/genome/analysis-workflows/blob/master/definitions/pipelines/germline_wgs.cwl) pipeline with [germline_wgs.yaml](https://github.com/genome/analysis-workflows/blob/master/example_data/germline_wgs.yaml) as values file.
I have several problems:
- Looks like [this](https://github.com/genome/analysis-workflows/blob/master/definitions/subworkflows/cnvkit_single_sample.cwl#L81) line is wrong - [cnvkit_vcf_export.cwl](https://github.com/genome/analysis-workflows/blob/master/definitions/tools/cnvkit_vcf_export.cwl) doesn't have `tumor_bam` input. 
- According to these lines: [germline_wgs.cwl#L88](https://github.com/genome/analysis-workflows/blob/master/definitions/pipelines/germline_wgs.cwl#L88), [single_sample_sv_callers.cwl#L29](https://github.com/genome/analysis-workflows/blob/master/definitions/subworkflows/single_sample_sv_callers.cwl#L29) and [cnvkit_single_sample.cwl#L24](https://github.com/genome/analysis-workflows/blob/master/definitions/subworkflows/cnvkit_single_sample.cwl#L24) - `cnvkit_reference_cnn` is required input.
But according to [cnvkit_batch.cwl#L67](https://github.com/genome/analysis-workflows/blob/master/definitions/tools/cnvkit_batch.cwl#L67) and tool help - it is optional.
I ask this question because [exome_workflow.tgz](https://github.com/genome/analysis-workflows/blob/master/example_data/exome_workflow.tgz) doesn't contain this file and [germline_wgs.yaml](https://github.com/genome/analysis-workflows/blob/master/example_data/germline_wgs.yaml) doesn't contain this input.

So - is this reference required? And if yes - how should I get it?
I find [this](https://cnvkit.readthedocs.io/en/stable/pipeline.html#reference) method - but I doesn't have these files either.

**Comment by tirohia** [comment]
Not sure whether this should go here, or a separate ticket opened. 

I had the same issue, and using cnvkit, pooling all available normal samples to get a reference.cnn file,

```cnvkit.py batch *.tumor.bam -n *.normal.bam -m wgs -f /blue/project/dev/data/references/hg38/hg38.fa --output-reference reference.cnn
```

 placing it in the analysis-workflows/example_data/ directory and adding the line:
```

cnvkit_reference_cnn: 
    class: File 
    path: "exome_workflow/reference.cnn" 
```
to your germline_wgs.yaml file in the analysis-workflows/example_data/ will work. 

For me though, that just takes me to the next error - there are a number of fields that are required by the germline_wgs.cwl pipeline that are not present in the example germline_wgs.yaml file. cnvkit_reference_cnn was the first, following on from that are:
merge_estimate_sv_distance
merge_max_distance
merge_min_svs
merge_same_type
merge_same_strand
vep_ensembl_assembly
vep_ensembl_species
vep_ensembl_version

The vep ones are easy to fix by adding to the germline_wgs.yaml:

```
vep_ensembl_assembly: "GRCh38"
vep_ensembl_species: "homo_sapiens"
vep_ensembl_version: "95"
```

I haven't been able to figure out what tools the merge variables are parameters for, so I've got nothing sensible to put in them.

**Comment by chrisamiller** [comment]
@apaul7 your PR #885 references this. Does it also resolve this issue?

**Comment by apaul7** [comment]
Yes, the germline wgs pipeline should no longer have the cnvkit pooled `reference.cnn` input as a requirement. I'll close the issue.
