### ISSUE TITLE
Alternative approach to making bigwig.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#732]
We should take an alternative approach to making the bigwig file of coverage in the WGS workflow. Instead of deepTools(which seems to hang on a small subset of samples with ample RAM), we should try using BEDTools and converting to bigwig. Example docs:
https://bedtools.readthedocs.io/en/latest/content/tools/genomecov.html
https://www.encodeproject.org/software/bedgraphtobigwig/

**Comment by chrisamiller** [comment]
mosdepth is going to have this natively in the next release: 
https://twitter.com/brent_p/status/1162889872455041024

**Comment by chrisamiller** [comment]
Ran across this today which may be of interest here:
https://github.com/cancerit/cgpBigWig

**Comment by chrisamiller** [comment]
@saimukund20 is working on this

**Comment by saimukund20** [comment]
should be done by this week

**Comment by chrisamiller** [comment]
#954 closed this for chipseq, which is great.  Sai, can you please add this to the two rnaseq pipelines as well?
