### ISSUE TITLE
Split Interval List fails with `scatter_count` of 1.

### ISSUE THREAD

**Issue by tmooney** [genome/analysis-workflows#790]
When this value: 
https://github.com/genome/analysis-workflows/blob/dc2c019c1aa24cc01b451a0f048cf94a35f163c4/definitions/tools/split_interval_list.cwl#L20
is set to `1`, Picard's `SplitIntervalList` behaves differently and treats the value of `OUTPUT=` as a filename rather than a directory name.  This special-case behavior leads to workflow failures, since we specify an existing directory as the value in all cases.

**Comment by jasonwalker80** [comment]
See #1002 for my first attempt at resolving this.
