### ISSUE TITLE
Traversing cache folder for vep

### ISSUE THREAD

**Issue by tatahin** [genome/analysis-workflows#832]
Hello!
I keep trying to run `germline_wgs.cwl` with BAMs and references from `example_data/exome_workflow` from repository (I had to add some files and values).
In `tools/vep.cwl` there is an input:
<pre>
    ensembl_species:
        type: string
        inputBinding:
            prefix: "--species"
            position: 12
       <b> doc: "ensembl species - Must be present in the cache directory. Examples: 'homo_sapiens' or 'mus_musculus'"</b>
</pre>

But no one parent step doesn't contain transmission of vep cache directory, so this step fail with error:
 ```
 
MSG: ERROR: Cache directory /home/bio/serge/analysis-workflows_TATAHIN_FORK/example_data/exome_workflow/homo_sapiens not found
STACK Bio::EnsEMBL::VEP::CacheDir::dir /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:311
STACK Bio::EnsEMBL::VEP::CacheDir::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /usr/bin/variant_effect_predictor.pl:225
Date (localtime)    = Wed Dec  4 08:20:18 2019
Ensembl API version = 95
 INFO [job annotate_variants] Max memory used: 0MiB
ERROR [job annotate_variants] Job error:
("Error collecting output for parameter 'annotated_vcf':\ndefinitions/tools/vep.cwl:126:13: Did not find output file with glob pattern: '['annotated.vcf']'", {})
WARNING [job annotate_variants] completed permanentFail
ERROR [step annotate_variants] Output is missing expected field file:///home/bio/serge/analysis-workflows_TATAHIN_FORK/definitions/subworkflows/germline_detect_variants.cwl#annotate_variants/annotated_vcf
ERROR [step annotate_variants] Output is missing expected field file:///home/bio/serge/analysis-workflows_TATAHIN_FORK/definitions/subworkflows/germline_detect_variants.cwl#annotate_variants/vep_summary
WARNING [step annotate_variants] completed permanentFail
INFO [workflow detect_variants] completed permanentFail
WARNING [step detect_variants] completed permanentFail
INFO [workflow ] completed permanentFail
```
Path of the cache directory (`/home/bio/serge/analysis-workflows_TATAHIN_FORK/example_data/exome_workflow/homo_sapiens`) is generated automatically from yaml file I use (fields `vep_cache_dir` and `vep_ensembl_species`), but this folder isn't mounting in vep-container.
 
I think it will be better to have option for traversing cache folder for vep. May be this decision will make pipeline slower, but it will be more versatile and meet the requirements of CWL.

**Comment by johnegarza** [comment]
@tatahin I believe #854 will have solved your problem. PR #883 is an update to our README that has instructions for downloading up-to-date example data for the pipeline you were testing, under the Quickstart/Data section.
