### ISSUE TITLE
docm call/filter

### ISSUE THREAD

**Issue by boyangzhao** [genome/analysis-workflows#833]
Hi - I was wondering the rationale behind the docm filter. As isn't DoCM a curated list of high quality validated cancer mutations, so if there’s a match to that in the DoCM in the variant call, shouldn’t this boost the confidence in the variant instead of being filtered out? In the workflow, it seems that DoCM variants are being filtered out because they are considered false positives?

**Comment by chrisamiller** [comment]
That's not quite the case, and we need to add more documentation around this to make it clear.  Here's how it works:

1) The DoCM sites are genotyped by the docm "caller", and passed through into the merged VCF if they have some evidence of presence.

2) If `filter_docm_variants` is set, sites that are ONLY called by docm (but not by any other caller) are flagged in the FILTER field (but are still present in the VCF for review, if desired).  Sites called by docm plus one or more additional callers (varscan, strelka, mutect, etc) will show up in the passing results.

In practice, the DoCM calls have high sensitivity and very low specificity - most turn out to be false positives.  If no other caller identifies the site, it is generally not a real mutation.  The goal of including DoCM at all is to give an opportunity for later manual review of those sites, to make sure they aren't completely missed. 

Hope this clears things up!

**Comment by boyangzhao** [comment]
Ah ok, thank you Chris! That makes sense. If we set filter_docm_variants to TRUE, a docm variant will be flagged with DOCM_ONLY in the FILTER field (by filter_vcf_docm.cwl in the docm_cle.cwl subworkflow). But as this is marked in the docm variant caller docm_cle.cwl, before seeing the results from the other variant callers. Does this mean, is it in docm_add_variants.cwl, where the docm vcf and other variant caller vcf are merged, that if the docm variant is also identified in other variant callers, the DOCM_ONLY would get removed and the FILTER gets flagged as PASS (or ".")? But I don't see e.g. --filteredrecordsmergetype set in the CombineVariants call in docm_add_variants.cwl to resolve conflicting filter fields; but I presume this step is where it resolves what you've mentioned as "Sites called by docm plus one or more additional callers (varscan, strelka, mutect, etc) will show up in the passing results."?

**Comment by chrisamiller** [comment]
Right - there are a few steps here:
1) under the `docm_cle.cwl` workflow, in `tools/filter_vcf_docm.cwl`, a docm VCF is created and the FILTER field is set (if filter_docm_variants is TRUE)
2)  sites from all non-docm callers get merged into one VCF
3) `tools/docm_add_variants.cwl` merges these two VCFs, preferentially keeping lines in the callers list when there is an intersection.  Thus, docm lines get added only if that site was not called by other callers.
4) when the filter_docm_variants is true, all of those docm-only sites will have the FILTER field set to DOCM_ONLY, so will not be listed as passing in the final VCF and won't appear in the final tsv.

**Comment by boyangzhao** [comment]
Got it, thank you!!

**Comment by chrisamiller** [comment]
I'm going to go ahead and leave this open as a reminder to us that the documentation in this area needs to be improved.  Thanks!

**Comment by boyangzhao** [comment]
A quick follow-up, Chris. I noticed that gnomADe_* seems to be a VEP custom annotation in the MGI workflow. What’s the difference between gnomADe_* and gnomAD_* (which is what is provided by VEP with the --af_gnomad option). In the gnomAD filter step (filter_vcf_custom_allele_freq.cwl), I set a default value for gnomad_field_name as gnomADe_AF. But it seems if I didn’t do the vep custom annotation with name “gnomADe”, there wouldn’t be gnomADe_AF and it wouldn’t actually filter anything; I should have instead used gnomAD_AF? Is this a hard filter or a soft filter to the vcf?
 
Also, do you filter the common allele frequencies using gnomAD(e)_AF? Why not with MAX_AF? As less than 0.001?

**Comment by apaul7** [comment]
Hi,
I just wanted to jump in and provide an explanation on the VEP custom annotations we use in the pipelines. We use the VEP custom annotation type to provide a relatively easy way for users to add their own annotations in the pipelines. Our specific use case is to annotate with our custom lifted over gnomAD VCF.

As you mentioned, when running VEP and providing the `--af_gnomad` flag annotates the variants with `gnomAD_*`. We annotate the variants with our custom gnomAD VCF as `gnomADe_*` to distinguish the source as our exome VCF.

With the release of gnomAD v3.0 we have started to annotate that VCF with `gnomADw_*`. This allows us to easily distinguish where the frequency came from and annotate with both the exome and genome frequencies.

We have the filter steps check to see if the provided VEP custom annotation contains the `gnomad_filter=true` option. If it does, the filtering steps will use that field + `_AF` as the gnomAD filtering field. If no VEP custom annotation field contains the `gnomad_filter=true` option it defaults to the VEP provided gnomAD annotation fields, `gnomAD_AF`. Previously our pipelines would require you to provide gnomAD VCF, annotate this VCF as the field `gnomADe_AF` and then filter based on that.

If you are not providing your own gnomAD VCF via the VEP custom annotation input you should be using the VEP provided gnomAD frequencies via the `gnomAD_*` fields.
-Alex

**Comment by boyangzhao** [comment]
Great thank you Alex. It's a lot clearer now!

**Comment by chrisamiller** [comment]
closed by https://github.com/genome/analysis-workflows/pull/952
