### ISSUE TITLE
DoCM runs GATK Haplotype Caller on entire genome

### ISSUE THREAD

**Issue by chrisamiller** [genome/analysis-workflows#834]
This tool only needs to be run over the regions that contain DoCM variants, but ends up being run on the entire genome/exome thanks to being passed in this interval file list.  The correct solution involves making an interval list that matches up with the docm VCF and only running over that region.

https://github.com/genome/analysis-workflows/blob/3034168d652bfa930ba09af20e473a4564a8010d/definitions/tools/docm_gatk_haplotype_caller.cwl#L42

**Comment by saimukund20** [comment]
Submitted PR for this
