### ISSUE TITLE
Remove mills input

### ISSUE THREAD

**Issue by chrisamiller** [genome/analysis-workflows#868]
The newest GATK resource bundle combines the mills and known indels files into one: `Mills_and_1000G_gold_standard.indels.hg38.vcf.gz`   We should drop the `mills` input throughout our genome alignment calling pipelines (all ending at bqsr, afaict).

**Comment by tmooney** [comment]
The tool CWL was updated to use a `known_sites` array input with the GATK4 update.  I'm inclined to say we should expose that array input up the chain instead of keeping separate with unique names--then a user could provide separate files or one combined file as they see fit.
