### ISSUE TITLE
Investigate improvements that could speed MarkDuplicates

### ISSUE THREAD

**Issue by chrisamiller** [genome/analysis-workflows#922]
Right now, mark_duplicates_and_sort takes about as much time as aligning reads on large WGS bams. Samblaster can be used inline, which should save a lot of I/O and improve speed:

    bwa mem <idxbase> samp.r1.fq samp.r2.fq | samblaster | samtools view -Sb - > samp.out.bam

Sorting could also potentially be added in that pipe, as in the speedseq pipeline. Back of the envelope, I'm guessing we could shave 4-8 hours off of WGS alignments with this approach.

**Comment by jasonwalker80** [comment]
Samblaster is already called in-line to add mate tags. However, it also is explicitly using the `-a` option to accept existing dup markings. I'm pretty sure this was explicitly configured this way to bypass samblaster duplicate marking and later use Picard MarkDuplicates. Also, if I recall correctly, there were reasons to use MarkDuplicates to maintain "functional equivalence" with other alignment workflows, ex. CCDG.

If we do want to run samblaster for duplicate marking, the changes should be fairly straightforward. As an example drop the `-a` from:
https://github.com/genome/docker-alignment_helper-cwl/blob/8c816f3cfdaa68091a83028611f712e50de5185c/alignment_helper.sh#L6

Then remove the Picard MarkDuplicates step from the alignment subworkflow.

**Comment by chrisamiller** [comment]
Yeah, I remember that old discussion, and I think that for somatic calling, at least, we don't care about being 100% aligned with the CCDG pipeline (they're not even using these workflows, right?)

**Comment by jasonwalker80** [comment]
Never mind... isn't the real issue merging? Speedseq as an example required all of the inputs for a sample and aligned in out BWA process/stream. Most of MGI's alignment workflows assume we will align each input separately in a scatter. Marking duplicates requires all reads in order to mark the correct duplicates.

**Comment by chrisamiller** [comment]
Ugh.  You're right.  Even though a lot of data comes in as single sets of fastqs these days, we can't rely on that. I also don't think merging the fastqs up front would be worth the hit we would take from that merge and from losing the ability to scatter the alignments.  Okay, closing this one up for now.

**Comment by chrisamiller** [comment]
Poking around, there's this option that's worth investigating
https://gatk.broadinstitute.org/hc/en-us/articles/360037224932-MarkDuplicatesSpark

> MarkDuplicatesSpark is optimized to run locally on a single machine by leveraging core parallelism that MarkDuplicates and SortSam cannot. It will typically run faster than MarkDuplicates and SortSam by a factor of 15% over the same data at 2 cores and will scale linearly to upwards of 16 cores. This means MarkDuplicatesSpark, even without access to a Spark cluster, is faster than MarkDuplicates.

**Comment by jasonwalker80** [comment]
In addition to spark/multi-threading improvements, we should re-evaluate the order of operations in our workflow. I don't believe older versions of MarkDuplicates would take multiple input files, so effectively MarkDuplicates can be a merge step as well rather than having a separate independent merge. As an example, check out the Broad Best Practice WDL:
https://github.com/gatk-workflows/gatk4-data-processing/blob/master/processing-for-variant-discovery-gatk4.wdl

**Comment by chrisamiller** [comment]
I tried to run the MarkDuplicatesSpark tool in the 'broadinstitute/gatk:4.1.3.0' container, but get this completely unhelpful error:

```
java.io.IOException: failure to login: javax.security.auth.login.LoginException: java.lang.NullPointerException: invalid null input: name
        at com.sun.security.auth.UnixPrincipal.<init>(UnixPrincipal.java:71)
        at com.sun.security.auth.module.UnixLoginModule.login(UnixLoginModule.java:133)
```
The documentation for this is rather lacking:
https://gatk.broadinstitute.org/hc/en-us/articles/360035889871--How-to-Run-Spark-enabled-GATK-tools-on-a-local-multi-core-machine

After some searching in non-gatk contexts, I suspect that this has something to do with not having the expected access permissions inside the docker container. Specifically, this stackoverflow question:
https://stackoverflow.com/questions/45198252/apache-spark-standalone-for-anonymous-uid-without-user-name 

```
Spark wants to be able to look up its UID in passwd. This integration kink can be resolved using nss_wrapper
. . . 
```

As well as this page:
 https://docs.cloudera.com/runtime/7.2.1/yarn-troubleshooting/topics/yarn-troubleshooting-docker.html
```
Problem statement
    Container fails shortly after start with the following exception:

    Exception in thread "main" org.apache.hadoop.security.KerberosAuthException: failure to login: javax.security.auth.login.LoginException: java.lang.NullPointerException: invalid null input: name
    	At com.sun.security.auth.UnixPrincipal.<init>(UnixPrincipal.java:71)
    	at com.sun.security.auth.module.UnixLoginModule.login(UnixLoginModule.java:133)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl. java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke( DelegatingMethodAccessorImpl.java:43)

Root cause
    The Hadoop UserGroupInformation class does not have access to the user permissions in the host system.
Resolution
    Mount the /etc/passwd to the image. More configuration issues can be found in upstream Hadoop 3.2 documentation: Launching Applications Using Docker Containers upstream documentation.
```

This question also suggests some fixes, all of which require low-level access that we don't have, due to our unusual cluster architecture: https://stackoverflow.com/questions/41864985/hadoop-ioexception-failure-to-login

At this point, I'm unclear how to proceed next here

**Comment by tmooney** [comment]
Out of curiosity, where are you trying to run this?  The newer cluster does supply an `/etc/passwd`, but on the older one I suspect you'd need to do something along the lines of this: https://confluence.ris.wustl.edu/pages/viewpage.action?pageId=27593241

**Comment by chrisamiller** [comment]
I've circled back to this, and it does indeed work on compute1, which is encouraging. I have a test running there, and the next step will be to see if we can fork the gatk container to add libnss-sss (or the equivalent) so that it will work on compute0 as well. If not, this becomes a non-backwards compatible change that breaks on compute0

**Comment by chrisamiller** [comment]
The current state of this is that Mark Duplicates isn't speedy, but it is not as time-consuming as previously though. The batch of jobs we were benchmarking on were during a time of high cluster usage, and time spent waiting to land a job was included in the cromwell chart.  The other side of this is that the Spark implementation does not seem to be substantially faster than the single core method on our cluster (despite using substantially more resources) seemingly due to excessive I/O.  I'm going to close this issue for now, and we can revisit at some later date if it becomes a bottleneck once again.
