### ISSUE TITLE
add downstream joint genotyping workflow

### ISSUE THREAD

**Issue by apaul7** [genome/analysis-workflows#933]
This workflow would take the outputs from the `pipelines/germline_exome_gvcf.cwl` and `pipelines/germline_wgs_gvcf.cwl` pipelines.
a brief outline of what I was thinking:
- merge input gvcfs
- genotype
- normalize
- annotate
- filter
- make tsv

**Comment by Sam16711** [comment]
Is it possible to output an unannotated, unfiltered vcf in the workflow after genotyping?

**Comment by apaul7** [comment]
Yes it can! Are there other things people would be interested in having as an output of the workflow?

For trios, I think running some family based QC would be nice. [Peddy](https://github.com/brentp/peddy) is one example but would require a new `family.ped` input file.

**Comment by apaul7** [comment]
closed by #962
