### ISSUE TITLE
Make sure all alignment workflows accept sequence (bam/fastq) inputs

### ISSUE THREAD

**Issue by chrisamiller** [genome/analysis-workflows#935]
Make a list of top-level pipelines that do alignment (germline, somatic, chipseq, rnaseq, bisulfite, etc and verify that they all accept the "sequence" type input.  Add it where needed, using existing workflows as a template.

**Comment by Sam16711** [comment]
Created issue #967 for the bisulfite sequencing pipeline.

**Comment by Sam16711** [comment]
Created issue #969 for umi molecular and umi duplex pipelines.

**Comment by Sam16711** [comment]
Created issue #970 for rnaseq pipelines.
