### ISSUE TITLE
implement blocklist_filter to sv_detect_variant for Germline WGS

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#943]
Feiyu - 
> I have already had the filter_vcf_blocklist_bedpe.cwl working as tool cwl and my version of germline_wgs_cle_analysis 
> pipeline cwl. But I want to tweak it into sv_detect_variant as optional so both cle and non-cle user can use

**Comment by dufeiyu** [comment]
The PR is merged. Resolve this issue.
